

#macro GLOADER_DEFAULT_ALPHA_CUTOFF 0.5
#macro GLOADER_DEFAULT_COLOR		[1, 1, 1, 1]
#macro GLOADER_DEFAULT_NORMAL		[0, 1, 1]
#macro GLOADER_DEFAULT_TEXCOORD		[0, 0]
#macro GLOADER_GAMMA				1.0/2.2

#macro GLOADER_DEFAULT_SCALE		[1, 1, 1]
#macro GLOADER_DEFAULT_ROTATION		[0, 0, 0, 1]
#macro GLOADER_DEFAULT_TRANSLATION	[0, 0, 0]

#macro GLOADER_DEFAULT_METAL		0
#macro GLOADER_DEFAULT_ROUGHNESS	0
#macro GLOADER_DEFAULT_EMISSIVE		0
#macro GLOADER_DEFAULT_